namespace Subnautica.Events.Patches.Fixes.Interact
{
    using HarmonyLib;

    using Subnautica.API.Features;

    using System;
    using System.Reflection;

    /// <summary>
    /// Suppresses EasyCraft and vanilla "No Power!" and "Don't Have Needed Ingredients"
    /// warning toasts in multiplayer when crafting with EasyCraft / external storage.
    /// </summary>
    [HarmonyPatch]
    public static class EasyCraftWarnings
    {
        private static bool _applied = false;

        /**
         * Intercepts ErrorMessage.AddWarning directly so that even if the warning
         * is generated by CrafterLogic.ConsumeResources or EasyCraft, it is suppressed.
         */
        [HarmonyPrefix]
        [HarmonyPatch(typeof(global::ErrorMessage), nameof(global::ErrorMessage.AddWarning))]
        private static bool AddWarningPrefix(string message)
        {
            if (!Network.IsMultiplayerActive)
            {
                return true;
            }

            if (string.IsNullOrEmpty(message))
            {
                return true;
            }

            if (IsCraftingWarning(message))
            {
                return false;
            }

            return true;
        }

        /**
         * Intercepts ErrorMessage.AddMessage as well in case the warning was sent as a normal message.
         */
        [HarmonyPrefix]
        [HarmonyPatch(typeof(global::ErrorMessage), nameof(global::ErrorMessage.AddMessage))]
        private static bool AddMessagePrefix(string message)
        {
            if (!Network.IsMultiplayerActive)
            {
                return true;
            }

            if (string.IsNullOrEmpty(message))
            {
                return true;
            }

            if (IsCraftingWarning(message))
            {
                return false;
            }

            return true;
        }

        private static bool IsCraftingWarning(string text)
        {
            try
            {
                if (Language.main != null)
                {
                    var noPower = Language.main.Get("NoPower");
                    if (!string.IsNullOrEmpty(noPower) && text.IndexOf(noPower, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        return true;
                    }

                    var noIngredients = Language.main.Get("DontHaveNeededIngredients");
                    if (!string.IsNullOrEmpty(noIngredients) && text.IndexOf(noIngredients, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        return true;
                    }
                }
            }
            catch
            {
            }

            // Fallback matching across common languages (English, Spanish, etc.)
            if (text.IndexOf("No Power", StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("Sin energ", StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("Needed Ingredients", StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("ingredientes necesarios", StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("Don't Have", StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("Dont Have", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return true;
            }

            return false;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(global::CrafterLogic), nameof(global::CrafterLogic.ConsumeEnergy))]
        private static bool CrafterLogicConsumeEnergyPrefix(ref bool __result)
        {
            if (!Network.IsMultiplayerActive)
            {
                return true;
            }

            // Power is managed and validated by the Server in multiplayer.
            // Client-side ConsumeEnergy must succeed so crafting does not abort.
            __result = true;
            return false;
        }

        /**
         * Called from the main patch initializer after all class-based Harmony
         * patches have been applied. Finds EasyCraft methods at runtime
         * and patches them only when EasyCraft is actually loaded.
         */
        public static void Apply(Harmony harmony)
        {
            if (_applied)
            {
                return;
            }

            try
            {
                Type easyCraftMain = null;
                foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                {
                    if (asm.GetName().Name == "EasyCraft_BZ")
                    {
                        easyCraftMain = asm.GetType("EasyCraft.Main");
                        break;
                    }
                }

                if (easyCraftMain == null)
                {
                    Log.Info("EasyCraftWarnings: EasyCraft_BZ not found yet — listening for AssemblyLoad.");
                    AppDomain.CurrentDomain.AssemblyLoad += (sender, args) =>
                    {
                        if (!_applied && args.LoadedAssembly.GetName().Name == "EasyCraft_BZ")
                        {
                            Apply(harmony);
                        }
                    };
                    return;
                }

                var showMessage = easyCraftMain.GetMethod(
                    "ShowMessage",
                    BindingFlags.Public | BindingFlags.Static,
                    null,
                    new[] { typeof(string) },
                    null);

                if (showMessage != null)
                {
                    var prefix = typeof(EasyCraftWarnings).GetMethod(
                        nameof(ShowMessagePrefix),
                        BindingFlags.NonPublic | BindingFlags.Static);

                    harmony.Patch(showMessage, prefix: new HarmonyMethod(prefix));
                    Log.Info("EasyCraftWarnings: ShowMessage suppression patched successfully.");
                }

                var consumeEnergy = easyCraftMain.GetMethod(
                    "ConsumeEnergy",
                    BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);

                if (consumeEnergy != null)
                {
                    var energyPrefix = typeof(EasyCraftWarnings).GetMethod(
                        nameof(EasyCraftConsumeEnergyPrefix),
                        BindingFlags.NonPublic | BindingFlags.Static);

                    harmony.Patch(consumeEnergy, prefix: new HarmonyMethod(energyPrefix));
                    Log.Info("EasyCraftWarnings: EasyCraft.Main.ConsumeEnergy patched successfully.");
                }

                _applied = true;
            }
            catch (Exception ex)
            {
                Log.Error($"EasyCraftWarnings.Apply failed: {ex}");
            }
        }

        /**
         * Prefix for EasyCraft.Main.ShowMessage.
         * Returns false to skip the original (suppress the warning) in multiplayer.
         */
        private static bool ShowMessagePrefix(ref bool __result)
        {
            if (!Network.IsMultiplayerActive)
            {
                return true;
            }

            __result = false;
            return false;
        }

        /**
         * Prefix for EasyCraft.Main.ConsumeEnergy.
         * Always returns true in multiplayer so EasyCraft energy check passes.
         */
        private static bool EasyCraftConsumeEnergyPrefix(ref bool __result)
        {
            if (!Network.IsMultiplayerActive)
            {
                return true;
            }

            __result = true;
            return false;
        }
    }
}
